package io.agent.helm.core.model;

/**
 * Token accounting for a single model call. {@code inputTokens} / {@code outputTokens} are the primary counts; the
 * remaining fields default to {@code 0} when not reported by the provider.
 *
 * @param inputTokens tokens consumed by the prompt.
 * @param outputTokens tokens generated by the completion.
 * @param cacheReadTokens cached prompt tokens reused from a previous call; defaults to {@code 0}.
 * @param cacheWriteTokens prompt tokens written to the provider cache for reuse; defaults to {@code 0}.
 * @param reasoningTokens tokens spent on internal reasoning (e.g. extended thinking); defaults to {@code 0}.
 */
public record TokenUsage(
        long inputTokens, long outputTokens, long cacheReadTokens, long cacheWriteTokens, long reasoningTokens) {
    /** Backwards-compatible 2-arg constructor; remaining counts default to {@code 0}. */
    public TokenUsage(long inputTokens, long outputTokens) {
        this(inputTokens, outputTokens, 0L, 0L, 0L);
    }
}
